# This is a basic workflow to help you get started with Actions

name: Build Canary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_nightly_release:
    runs-on: macos-12
    
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v3
      
      - name: "Select Xcode 13.3.1"
        uses: devbotsxyz/xcode-select@main
        with:
          version: "13.3.1"
      
      - name: "Import Certificate: Development"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      
      - name: "Import Certificate: Distribution"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
          
      - name: "Update Xcode Team ID"
        run: |
            TEAMID=`awk -F '=' '/DEVELOPMENT_TEAM/ {print $2; exit}' Swiftcord.xcodeproj/project.pbxproj`
            sed -i '' "s/$TEAMID/ RJNC97Y8QD;/g" Swiftcord.xcodeproj/project.pbxproj
          
      - name: "Archive"
        uses: devbotsxyz/xcode-archive@v1
        with:
          workspace: Swiftcord.xcworkspace
          scheme: Swiftcord
          configuration: Release
          
      - name: "Export & Sign Release Build"
        uses: devbotsxyz/xcode-export-archive@main
        with:
          workspace: Swiftcord.xcworkspace
          scheme: Swiftcord
          
      - name: Install create-dmg
        run: npm install --global create-dmg
        
      - name: Make Release Dmg
        run: create-dmg Export/Swiftcord.app
      
      - name: "Notarize Release Build"
        run: |
            xcrun notarytool store-credentials "AC_PASSWORD" --apple-id ${{ secrets.APPSTOREONNECT_USERNAME }} --team-id RJNC97Y8QD --password ${{ secrets.APPSTORECONNECT_PASSWORD }}
            xcrun notarytool submit Swiftcord*.dmg --keychain-profile "AC_PASSWORD" --wait
          
      - name: "Staple Release Build"
        run: xcrun stapler staple Swiftcord.dmg
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: Swiftcord_Canary # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: Swiftcord*.dmg

